{% set name = "nomad-parser-plugins-workflow" %}
{% set version = "1.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_parser_plugins_workflow-{{ version }}.tar.gz
  sha256: 37716b34ed3854a218b84a888c0bc352e8127c97df88080a117b3f578f3fdc22

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=8.0
    - pip
  run:
    - python >={{ python_min }}
    - nomad-lab >=1.3.13
    - nomad-schema-plugin-simulation-workflow >=1.0.1
    - nomad-schema-plugin-run >=1.0.1
    - lxml >=5.2
    - asr ==0.4.1
    - xarray >=0.20.1
    - phonopy >=2.35,<=2.38
    - h5py >=3.11.0
    - pydantic >=1.10.8
    - netcdf4
    - h5netcdf

test:
  imports:
    - workflowparsers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nomad-coe/workflow-parsers
  summary: Collection of NOMAD parsers for workflow engines.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
